# Generated by Django 5.1.7 on 2025-05-16 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CovidRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('organization', models.CharField(max_length=255)),
                ('childrens_hospital', models.BooleanField()),
                ('admissions', models.IntegerField()),
                ('forecast', models.BooleanField()),
                ('chronos_pred', models.IntegerField()),
                ('conformal_naive_pred', models.IntegerField()),
                ('arima_pred', models.IntegerField()),
                ('transformer_pred', models.IntegerField()),
                ('xgb_pred', models.IntegerField()),
            ],
        ),
    ]
