# Generated by Django 5.1.7 on 2025-05-17 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_ingester', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covidrecord',
            name='admissions',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='covidrecord',
            name='arima_pred',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='covidrecord',
            name='chronos_pred',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='covidrecord',
            name='conformal_naive_pred',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='covidrecord',
            name='transformer_pred',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='covidrecord',
            name='xgb_pred',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
